import express from "express";
import { createServer as createHttpServer } from "http";
import { Server as SocketServer } from "socket.io";
import { createServer as createViteServer } from "vite";
import path from "path";
import axios from "axios";

async function startServer() {
  const app = express();
  const httpServer = createHttpServer(app);
  const io = new SocketServer(httpServer, {
    cors: {
      origin: "*",
      methods: ["GET", "POST"]
    }
  });

  const PORT = 3000;

  app.use(express.json());

  // Coding Compiler Proxy (Judge0 or similar)
  app.post("/api/compile", async (req, res) => {
    const { source_code, language_id, stdin } = req.body;
    
    // Check for API key
    const apiKey = process.env.JUDGE0_API_KEY;
    
    if (!apiKey || apiKey === "MY_JUDGE0_API_KEY") {
      // Simulation logic for common beginner code
      console.log("Using simulation mode for compiler");
      let output = "";
      if (source_code.includes('print(')) {
        const matches = source_code.matchAll(/print\((['"])(.*?)\1\)/g);
        for (const match of matches) {
          output += match[2] + "\n";
        }
      }
      
      if (output) {
        return res.json({ stdout: output.trim() });
      }
      
      return res.json({ error: "Judge0 API Key missing. Please configure JUDGE0_API_KEY in secrets." });
    }

    try {
      const response = await axios.post("https://judge0-ce.p.rapidapi.com/submissions", {
        source_code,
        language_id,
        stdin
      }, {
        headers: {
          "x-rapidapi-key": apiKey,
          "x-rapidapi-host": "judge0-ce.p.rapidapi.com",
          "Content-Type": "application/json"
        },
        params: { base64_encoded: "false", wait: "true" }
      });
      res.json(response.data);
    } catch (error: any) {
      res.status(500).json({ error: error.message });
    }
  });

  // Quiz Battle Matchmaking
  const matchmakingQueue = new Map<string, any[]>(); // key: class-subject, value: array of sockets
  const activeRooms = new Map<string, any>();

  io.on("connection", (socket) => {
    console.log("User connected:", socket.id);

    socket.on("find-match", ({ className, subject, user }) => {
      const key = `${className}-${subject}`;
      if (!matchmakingQueue.has(key)) {
        matchmakingQueue.set(key, []);
      }
      const queue = matchmakingQueue.get(key)!;
      
      // Check if user is already in queue
      if (queue.find(p => p.user.uid === user.uid)) return;

      queue.push({ socket, user });

      if (queue.length >= 2) {
        const p1 = queue.shift();
        const p2 = queue.shift();
        const roomId = `room-${Date.now()}`;

        p1.socket.join(roomId);
        p2.socket.join(roomId);

        const roomData = {
          id: roomId,
          players: [
            { id: p1.socket.id, uid: p1.user.uid, name: p1.user.name, score: 0, currentIdx: 0, timeTaken: 0, finished: false },
            { id: p2.socket.id, uid: p2.user.uid, name: p2.user.name, score: 0, currentIdx: 0, timeTaken: 0, finished: false }
          ],
          questions: [], // Will be generated by one of the clients and synced
          startTime: Date.now()
        };

        activeRooms.set(roomId, roomData);
        io.to(roomId).emit("match-found", roomData);
      }
    });

    socket.on("sync-questions", ({ roomId, questions }) => {
      const room = activeRooms.get(roomId);
      if (room) {
        room.questions = questions;
        io.to(roomId).emit("questions-ready", questions);
      }
    });

    socket.on("update-progress", ({ roomId, score, currentIdx, timeTaken, finished }) => {
      const room = activeRooms.get(roomId);
      if (room) {
        const player = room.players.find((p: any) => p.id === socket.id);
        if (player) {
          player.score = score;
          player.currentIdx = currentIdx;
          player.timeTaken = timeTaken;
          player.finished = finished;
        }
        io.to(roomId).emit("room-update", room);

        // If both finished, trigger end
        if (room.players.every((p: any) => p.finished)) {
          io.to(roomId).emit("battle-finished", room);
          activeRooms.delete(roomId);
        }
      }
    });

    socket.on("leave-queue", ({ className, subject, user }) => {
      const key = `${className}-${subject}`;
      const queue = matchmakingQueue.get(key);
      if (queue) {
        matchmakingQueue.set(key, queue.filter(p => p.user.uid !== user.uid));
      }
    });

    socket.on("disconnect", () => {
      console.log("User disconnected:", socket.id);
      // Clean up queues
      matchmakingQueue.forEach((queue, key) => {
        matchmakingQueue.set(key, queue.filter(p => p.socket.id !== socket.id));
      });
    });
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  httpServer.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
